In [12]:
import sys
!{sys.executable} -m pip install pandas
!{sys.executable} -m pip install matplotlib
!{sys.executable} -m pip install seaborn

Requirement already satisfied: pandas in c:\users\kssy\appdata\local\python\pythoncore-3.14-64\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kssy\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kssy\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kssy\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kssy\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\kssy\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: matplotlib in c:\users\kssy\appdata\local\python\pythoncore-3.14-64\lib\site-packages (3.10.7)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\kssy\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\kssy\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\kssy\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\kssy\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in c:\users\kssy\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib) (2.3.3)
Requirement already satisfied: packaging>=20.0 in c:\users\kssy\appdata\roaming\python\python314\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\kssy\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\kssy\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\kssy\appdata\roaming\python\python314\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\kssy\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: seaborn in c:\users\kssy\appdata\local\python\pythoncore-3.14-64\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\kssy\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: pandas>=1.2 in c:\users\kssy\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\kssy\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from seaborn) (3.10.7)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\kssy\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\kssy\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\kssy\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\kssy\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\kssy\appdata\roaming\python\python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\kssy\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\kssy\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\kssy\appdata\roaming\python\python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kssy\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kssy\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\kssy\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [13]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

files_names = [
    'EdStatsCountry.csv',
    'EdStatsCountry-Series.csv',
    'EdStatsData.csv',
    'EdStatsFootNote.csv',
    'EdStatsSeries.csv'
]

for files in files_names:
        print(f"{files}")
        df = pd.read_csv(files)
        display(df.head())

EdStatsCountry.csv

,Country Code,Short Name,Table Name,Long Name,2-alpha code,Currency Unit,Special Notes,Region,Income Group,WB-2 code,National accounts base year,National accounts reference year,SNA price valuation,Lending category,Other groups,System of National Accounts,Alternative conversion factor,PPP survey year,Balance of Payments Manual in use,External debt Reporting status,System of trade,Government Accounting concept,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Latest water withdrawal data,Unnamed: 31
0,ABW,Aruba,Aruba,Aruba,AW,Aruban florin,SNA data for 2000-2011 are updated from offici...,Latin America & Caribbean,High income: nonOECD,AW,2000,NaN,Value added at basic prices (VAB),NaN,NaN,Country uses the 1993 System of National Accou...,NaN,NaN,"IMF Balance of Payments Manual, 6th edition.",NaN,Special trade system,NaN,NaN,2010,NaN,NaN,Yes,NaN,NaN,2012.0,NaN,NaN
1,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,2002/03,NaN,Value added at basic prices (VAB),IDA,HIPC,Country uses the 1993 System of National Accou...,NaN,NaN,NaN,Actual,General trade system,Consolidated central government,General Data Dissemination System (GDDS),1979,"Multiple Indicator Cluster Survey (MICS), 2010/11","Integrated household survey (IHS), 2008",NaN,2013/14,NaN,2012.0,2000,NaN
2,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,"April 2013 database update: Based on IMF data,...",Sub-Saharan Africa,Upper middle income,AO,2002,NaN,Value added at producer prices (VAP),IBRD,NaN,Country uses the 1993 System of National Accou...,1991–96,2005,"IMF Balance of Payments Manual, 6th edition.",Actual,Special trade system,Budgetary central government,General Data Dissemination System (GDDS),1970,"Malaria Indicator Survey (MIS), 2011","Integrated household survey (IHS), 2008",NaN,2015,NaN,NaN,2005,NaN
3,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,NaN,Europe & Central Asia,Upper middle income,AL,Original chained constant price data are resca...,1996.0,Value added at basic prices (VAB),IBRD,NaN,Country uses the 1993 System of National Accou...,NaN,Rolling,"IMF Balance of Payments Manual, 6th edition.",Actual,General trade system,Budgetary central government,General Data Dissemination System (GDDS),2011,"Demographic and Health Survey (DHS), 2008/09",Living Standards Measurement Study Survey (LSM...,Yes,2012,2010.0,2012.0,2006,NaN
4,AND,Andorra,Andorra,Principality of Andorra,AD,Euro,NaN,Europe & Central Asia,High income: nonOECD,AD,1990,NaN,NaN,NaN,NaN,Country uses the 1968 System of National Accou...,NaN,NaN,NaN,NaN,Special trade system,NaN,NaN,2011. Population figures compiled from adminis...,NaN,NaN,Yes,NaN,NaN,2006.0,NaN,NaN

EdStatsCountry-Series.csv

,CountryCode,SeriesCode,DESCRIPTION,Unnamed: 3
0,ABW,SP.POP.TOTL,Data sources : United Nations World Population...,NaN
1,ABW,SP.POP.GROW,Data sources: United Nations World Population ...,NaN
2,AFG,SP.POP.GROW,Data sources: United Nations World Population ...,NaN
3,AFG,NY.GDP.PCAP.PP.CD,Estimates are based on regression.,NaN
4,AFG,SP.POP.TOTL,Data sources : United Nations World Population...,NaN

EdStatsData.csv

,Country Name,Country Code,Indicator Name,Indicator Code,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2020,2025,2030,2035,2040,2045,2050,2055,2060,2065,2070,2075,2080,2085,2090,2095,2100,Unnamed: 69
0,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.GPI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Arab World,ARB,"Adjusted net enrolment rate, primary, both sex...",SE.PRM.TENR,54.822121,54.894138,56.209438,57.267109,57.991138,59.36554,60.999962,61.92268,62.69342,64.383186,65.617767,66.085152,66.608139,67.290451,68.510094,69.033211,69.944908,71.04187,71.693779,71.699097,71.995819,72.602837,70.032722,70.464821,72.645683,71.81176,73.903511,74.425201,75.110817,76.254318,77.245682,78.800522,80.051399,80.805389,81.607063,82.489487,82.685509,83.280342,84.011871,84.195961,85.211998,85.24514,86.101669,85.51194,85.320152,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

EdStatsFootNote.csv

  CountryCode      SeriesCode    Year          DESCRIPTION  Unnamed: 4
0         ABW  SE.PRE.ENRL.FE  YR2001  Country estimation.         NaN
1         ABW  SE.TER.TCHR.FE  YR2005  Country estimation.         NaN
2         ABW  SE.PRE.TCHR.FE  YR2000  Country estimation.         NaN
3         ABW  SE.SEC.ENRL.GC  YR2004  Country estimation.         NaN
4         ABW     SE.PRE.TCHR  YR2006  Country estimation.         NaN

EdStatsSeries.csv

,Series Code,Topic,Indicator Name,Short definition,Long definition,Unit of measure,Periodicity,Base Period,Other notes,Aggregation method,Limitations and exceptions,Notes from original source,General comments,Source,Statistical concept and methodology,Development relevance,Related source links,Other web links,Related indicators,License Type,Unnamed: 20
0,BAR.NOED.1519.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 15-19 with...,Percentage of female population age 15-19 with...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Robert J. Barro and Jong-Wha Lee: http://www.b...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BAR.NOED.1519.ZS,Attainment,Barro-Lee: Percentage of population age 15-19 ...,Percentage of population age 15-19 with no edu...,Percentage of population age 15-19 with no edu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Robert J. Barro and Jong-Wha Lee: http://www.b...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BAR.NOED.15UP.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 15+ with n...,Percentage of female population age 15+ with n...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Robert J. Barro and Jong-Wha Lee: http://www.b...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BAR.NOED.15UP.ZS,Attainment,Barro-Lee: Percentage of population age 15+ wi...,Percentage of population age 15+ with no educa...,Percentage of population age 15+ with no educa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Robert J. Barro and Jong-Wha Lee: http://www.b...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BAR.NOED.2024.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 20-24 with...,Percentage of female population age 20-24 with...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Robert J. Barro and Jong-Wha Lee: http://www.b...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# ===========================================
# ANALYSE DU FICHIER EdStatsCountry.csv
# ===========================================

print("=" * 50)
print("ANALYSE DE EdStatsCountry.csv")
print("=" * 50)

# Chargement du fichier
df_country = pd.read_csv('EdStatsCountry.csv')

# 1. Définition de ce que représente une ligne
print("\n1. DÉFINITION D'UNE LIGNE:")
print("Une ligne représente un pays avec ses informations géographiques et économiques.")
print("Chaque ligne = un pays unique")

# 2. Affichage des premières lignes pour comprendre la structure
print("\n2. PREMIÈRES LIGNES:")
display(df_country.head())

# 3. Calcul du nombre de lignes et colonnes
print(f"\n3. DIMENSIONS:")
print(f"Nombre de lignes: {df_country.shape[0]}")
print(f"Nombre de colonnes: {df_country.shape[1]}")

# 4. Informations sur les colonnes
print(f"\n4. INFORMATIONS SUR LES COLONNES:")
df_country.info()

# 5. Calcul du nombre de doublons
print(f"\n5. DOUBLONS:")
nb_doublons = df_country.duplicated().sum()
print(f"Nombre de doublons: {nb_doublons}")

if nb_doublons > 0:
    print("Suppression des doublons...")
    df_country = df_country.drop_duplicates()
    print(f"Nouveau nombre de lignes après suppression: {df_country.shape[0]}")
else:
    print("Aucun doublon trouvé.")

# 6. Proportion de valeurs manquantes par colonne
print(f"\n6. VALEURS MANQUANTES PAR COLONNE:")
missing_prop = df_country.isnull().sum() / len(df_country) * 100
print(missing_prop)

# 7. Identification des colonnes inutilisables (trop de valeurs manquantes)
print(f"\n7. COLONNES INUTILISABLES (plus de 50% de valeurs manquantes):")
colonnes_inutilisables = missing_prop[missing_prop > 50].index.tolist()
print(f"Colonnes à supprimer: {colonnes_inutilisables}")

if colonnes_inutilisables:
    print("Suppression des colonnes inutilisables...")
    df_country = df_country.drop(columns=colonnes_inutilisables)
    print(f"Nouvelles dimensions: {df_country.shape}")

# 8. Statistiques descriptives pour les colonnes numériques
print(f"\n8. STATISTIQUES DESCRIPTIVES (colonnes numériques):")
colonnes_numeriques = df_country.select_dtypes(include=['number']).columns
if len(colonnes_numeriques) > 0:
    print(df_country[colonnes_numeriques].describe())
else:
    print("Aucune colonne numérique trouvée.")

# 9. Analyse des colonnes catégorielles
print(f"\n9. ANALYSE DES COLONNES CATÉGORIELLES:")
colonnes_categorielles = df_country.select_dtypes(include=['object']).columns
for col in colonnes_categorielles:
    print(f"\n--- {col} ---")
    print(f"Nombre de valeurs uniques: {df_country[col].nunique()}")
    print("Top 10 des valeurs les plus fréquentes:")
    print(df_country[col].value_counts().head(10))

print("\n" + "=" * 50)

==================================================
ANALYSE DE EdStatsCountry.csv
==================================================

1. DÉFINITION D'UNE LIGNE:
Une ligne représente un pays avec ses informations géographiques et économiques.
Chaque ligne = un pays unique

2. PREMIÈRES LIGNES:

,Country Code,Short Name,Table Name,Long Name,2-alpha code,Currency Unit,Special Notes,Region,Income Group,WB-2 code,National accounts base year,National accounts reference year,SNA price valuation,Lending category,Other groups,System of National Accounts,Alternative conversion factor,PPP survey year,Balance of Payments Manual in use,External debt Reporting status,System of trade,Government Accounting concept,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Latest water withdrawal data,Unnamed: 31
0,ABW,Aruba,Aruba,Aruba,AW,Aruban florin,SNA data for 2000-2011 are updated from offici...,Latin America & Caribbean,High income: nonOECD,AW,2000,NaN,Value added at basic prices (VAB),NaN,NaN,Country uses the 1993 System of National Accou...,NaN,NaN,"IMF Balance of Payments Manual, 6th edition.",NaN,Special trade system,NaN,NaN,2010,NaN,NaN,Yes,NaN,NaN,2012.0,NaN,NaN
1,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,2002/03,NaN,Value added at basic prices (VAB),IDA,HIPC,Country uses the 1993 System of National Accou...,NaN,NaN,NaN,Actual,General trade system,Consolidated central government,General Data Dissemination System (GDDS),1979,"Multiple Indicator Cluster Survey (MICS), 2010/11","Integrated household survey (IHS), 2008",NaN,2013/14,NaN,2012.0,2000,NaN
2,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,"April 2013 database update: Based on IMF data,...",Sub-Saharan Africa,Upper middle income,AO,2002,NaN,Value added at producer prices (VAP),IBRD,NaN,Country uses the 1993 System of National Accou...,1991–96,2005,"IMF Balance of Payments Manual, 6th edition.",Actual,Special trade system,Budgetary central government,General Data Dissemination System (GDDS),1970,"Malaria Indicator Survey (MIS), 2011","Integrated household survey (IHS), 2008",NaN,2015,NaN,NaN,2005,NaN
3,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,NaN,Europe & Central Asia,Upper middle income,AL,Original chained constant price data are resca...,1996.0,Value added at basic prices (VAB),IBRD,NaN,Country uses the 1993 System of National Accou...,NaN,Rolling,"IMF Balance of Payments Manual, 6th edition.",Actual,General trade system,Budgetary central government,General Data Dissemination System (GDDS),2011,"Demographic and Health Survey (DHS), 2008/09",Living Standards Measurement Study Survey (LSM...,Yes,2012,2010.0,2012.0,2006,NaN
4,AND,Andorra,Andorra,Principality of Andorra,AD,Euro,NaN,Europe & Central Asia,High income: nonOECD,AD,1990,NaN,NaN,NaN,NaN,Country uses the 1968 System of National Accou...,NaN,NaN,NaN,NaN,Special trade system,NaN,NaN,2011. Population figures compiled from adminis...,NaN,NaN,Yes,NaN,NaN,2006.0,NaN,NaN

3. DIMENSIONS:
Nombre de lignes: 241
Nombre de colonnes: 32

4. INFORMATIONS SUR LES COLONNES:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 32 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Country Code                                       241 non-null    object
 1   Short Name                                         241 non-null    object
 2   Table Name                                         241 non-null    object
 3   Long Name                                          241 non-null    object
 4   2-alpha code                                       238 non-null    object
 5   Currency Unit                                      215 non-null    object
 6   Special Notes                                      145 non-null    object
 7   Region                                             214 non-null    object
 8   Income Group                                       214 non-null    object
 9   WB-2 code                                          240 non-null    object
 10  National accounts base year                        205 non-null    object
 11  National accounts reference year                   32 non-null     float64
 12  SNA price valuation                                197 non-null    object
 13  Lending category                                   144 non-null    object
 14  Other groups                                       58 non-null     object
 15  System of National Accounts                        215 non-null    object
 16  Alternative conversion factor                      47 non-null     object
 17  PPP survey year                                    145 non-null    object
 18  Balance of Payments Manual in use                  181 non-null    object
 19  External debt Reporting status                     124 non-null    object
 20  System of trade                                    200 non-null    object
 21  Government Accounting concept                      161 non-null    object
 22  IMF data dissemination standard                    181 non-null    object
 23  Latest population census                           213 non-null    object
 24  Latest household survey                            141 non-null    object
 25  Source of most recent Income and expenditure data  160 non-null    object
 26  Vital registration complete                        111 non-null    object
 27  Latest agricultural census                         142 non-null    object
 28  Latest industrial data                             107 non-null    float64
 29  Latest trade data                                  185 non-null    float64
 30  Latest water withdrawal data                       179 non-null    object
 31  Unnamed: 31                                        0 non-null      float64
dtypes: float64(4), object(28)
memory usage: 60.4+ KB

5. DOUBLONS:
Nombre de doublons: 0
Aucun doublon trouvé.

6. VALEURS MANQUANTES PAR COLONNE:
Country Code                                           0.000000
Short Name                                             0.000000
Table Name                                             0.000000
Long Name                                              0.000000
2-alpha code                                           1.244813
Currency Unit                                         10.788382
Special Notes                                         39.834025
Region                                                11.203320
Income Group                                          11.203320
WB-2 code                                              0.414938
National accounts base year                           14.937759
National accounts reference year                      86.721992
SNA price valuation                                   18.257261
Lending category                                      40.248963
Other groups                                          75.933610
System of National Accounts                           10.788382
Alternative conversion factor                         80.497925
PPP survey year                                       39.834025
Balance of Payments Manual in use                     24.896266
External debt Reporting status                        48.547718
System of trade                                       17.012448
Government Accounting concept                         33.195021
IMF data dissemination standard                       24.896266
Latest population census                              11.618257
Latest household survey                               41.493776
Source of most recent Income and expenditure data     33.609959
Vital registration complete                           53.941909
Latest agricultural census                            41.078838
Latest industrial data                                55.601660
Latest trade data                                     23.236515
Latest water withdrawal data                          25.726141
Unnamed: 31                                          100.000000
dtype: float64

7. COLONNES INUTILISABLES (plus de 50% de valeurs manquantes):
Colonnes à supprimer: ['National accounts reference year', 'Other groups', 'Alternative conversion factor', 'Vital registration complete', 'Latest industrial data', 'Unnamed: 31']
Suppression des colonnes inutilisables...
Nouvelles dimensions: (241, 26)

8. STATISTIQUES DESCRIPTIVES (colonnes numériques):
       Latest trade data
count         185.000000
mean         2010.994595
std             2.569675
min          1995.000000
25%          2011.000000
50%          2012.000000
75%          2012.000000
max          2012.000000

9. ANALYSE DES COLONNES CATÉGORIELLES:

--- Country Code ---
Nombre de valeurs uniques: 241
Top 10 des valeurs les plus fréquentes:
Country Code
ABW    1
AFG    1
AGO    1
ALB    1
AND    1
ARB    1
ARE    1
ARG    1
ARM    1
ASM    1
Name: count, dtype: int64

--- Short Name ---
Nombre de valeurs uniques: 241
Top 10 des valeurs les plus fréquentes:
Short Name
Aruba                   1
Afghanistan             1
Angola                  1
Albania                 1
Andorra                 1
Arab World              1
United Arab Emirates    1
Argentina               1
Armenia                 1
American Samoa          1
Name: count, dtype: int64

--- Table Name ---
Nombre de valeurs uniques: 241
Top 10 des valeurs les plus fréquentes:
Table Name
Aruba                   1
Afghanistan             1
Angola                  1
Albania                 1
Andorra                 1
Arab World              1
United Arab Emirates    1
Argentina               1
Armenia                 1
American Samoa          1
Name: count, dtype: int64

--- Long Name ---
Nombre de valeurs uniques: 241
Top 10 des valeurs les plus fréquentes:
Long Name
Aruba                           1
Islamic State of Afghanistan    1
People's Republic of Angola     1
Republic of Albania             1
Principality of Andorra         1
Arab World                      1
United Arab Emirates            1
Argentine Republic              1
Republic of Armenia             1
American Samoa                  1
Name: count, dtype: int64

--- 2-alpha code ---
Nombre de valeurs uniques: 238
Top 10 des valeurs les plus fréquentes:
2-alpha code
AW    1
AF    1
AO    1
AL    1
AD    1
1A    1
AE    1
AR    1
AM    1
AS    1
Name: count, dtype: int64

--- Currency Unit ---
Nombre de valeurs uniques: 152
Top 10 des valeurs les plus fréquentes:
Currency Unit
Euro                            23
U.S. dollar                     14
CFA franc                       14
East Caribbean dollar            6
Australian dollar                3
Pound sterling                   3
Danish krone                     3
Netherlands Antilles guilder     2
Swiss franc                      2
Israeli new shekel               2
Name: count, dtype: int64

--- Special Notes ---
Nombre de valeurs uniques: 131
Top 10 des valeurs les plus fréquentes:
Special Notes
April 2012 database update: Based on official government statistics, national accounts data were revised for 2000 onward; the base year changed to 2006.                                                                                             6
Fiscal year end: March 31; reporting period for national accounts data: CY.                                                                                                                                                                          4
Fiscal year end: June 30; reporting period for national accounts data: CY.                                                                                                                                                                           3
April 2013 database update: Based on IMF data, national accounts data were revised for 2000 onward; the base year changed to 2000.                                                                                                                   2
Fiscal year end: March 31; reporting period for national accounts data: FY.                                                                                                                                                                          2
Fiscal year end: September 30; reporting period for national accounts data: CY.                                                                                                                                                                      2
Fiscal year end: June 30; reporting period for national accounts data: FY.                                                                                                                                                                           2
April 2013 database update: Based on IMF data, national accounts data were revised for 2000 onward; the base year changed to 2002.                                                                                                                   1
Fiscal year end: March 20; reporting period for national accounts data: FY (from 2013 are CY). National accounts data are sourced from the IMF and differ from the Central Statistics Organization numbers due to exclusion of the opium economy.    1
SNA data for 2000-2011 are updated from official government statistics; 1994-1999 from UN databases. Base year has changed from 1995 to 2000.                                                                                                        1
Name: count, dtype: int64

--- Region ---
Nombre de valeurs uniques: 7
Top 10 des valeurs les plus fréquentes:
Region
Europe & Central Asia         57
Sub-Saharan Africa            48
Latin America & Caribbean     41
East Asia & Pacific           36
Middle East & North Africa    21
South Asia                     8
North America                  3
Name: count, dtype: int64

--- Income Group ---
Nombre de valeurs uniques: 5
Top 10 des valeurs les plus fréquentes:
Income Group
Upper middle income     55
Lower middle income     50
High income: nonOECD    44
Low income              34
High income: OECD       31
Name: count, dtype: int64

--- WB-2 code ---
Nombre de valeurs uniques: 240
Top 10 des valeurs les plus fréquentes:
WB-2 code
AW    1
AF    1
AO    1
AL    1
AD    1
1A    1
AE    1
AR    1
AM    1
AS    1
Name: count, dtype: int64

--- National accounts base year ---
Nombre de valeurs uniques: 43
Top 10 des valeurs les plus fréquentes:
National accounts base year
2005                                                  34
Original chained constant price data are rescaled.    28
2000                                                  25
2006                                                  19
1990                                                  11
2007                                                   9
2004                                                   8
2010                                                   6
2003                                                   5
1999                                                   4
Name: count, dtype: int64

--- SNA price valuation ---
Nombre de valeurs uniques: 2
Top 10 des valeurs les plus fréquentes:
SNA price valuation
Value added at basic prices (VAB)       163
Value added at producer prices (VAP)     34
Name: count, dtype: int64

--- Lending category ---
Nombre de valeurs uniques: 3
Top 10 des valeurs les plus fréquentes:
Lending category
IBRD     67
IDA      59
Blend    18
Name: count, dtype: int64

--- System of National Accounts ---
Nombre de valeurs uniques: 3
Top 10 des valeurs les plus fréquentes:
System of National Accounts
Country uses the 1993 System of National Accounts methodology.    165
Country uses the 1968 System of National Accounts methodology.     42
Country uses the 2008 System of National Accounts methodology.      8
Name: count, dtype: int64

--- PPP survey year ---
Nombre de valeurs uniques: 3
Top 10 des valeurs les plus fréquentes:
PPP survey year
2005       98
Rolling    37
2011       10
Name: count, dtype: int64

--- Balance of Payments Manual in use ---
Nombre de valeurs uniques: 1
Top 10 des valeurs les plus fréquentes:
Balance of Payments Manual in use
IMF Balance of Payments Manual, 6th edition.    181
Name: count, dtype: int64

--- External debt Reporting status ---
Nombre de valeurs uniques: 3
Top 10 des valeurs les plus fréquentes:
External debt Reporting status
Actual         107
Estimate        11
Preliminary      6
Name: count, dtype: int64

--- System of trade ---
Nombre de valeurs uniques: 2
Top 10 des valeurs les plus fréquentes:
System of trade
General trade system    106
Special trade system     94
Name: count, dtype: int64

--- Government Accounting concept ---
Nombre de valeurs uniques: 2
Top 10 des valeurs les plus fréquentes:
Government Accounting concept
Consolidated central government    95
Budgetary central government       66
Name: count, dtype: int64

--- IMF data dissemination standard ---
Nombre de valeurs uniques: 2
Top 10 des valeurs les plus fréquentes:
IMF data dissemination standard
General Data Dissemination System (GDDS)      110
Special Data Dissemination Standard (SDDS)     71
Name: count, dtype: int64

--- Latest population census ---
Nombre de valeurs uniques: 27
Top 10 des valeurs les plus fréquentes:
Latest population census
2011    59
2010    49
2012    18
2009    14
2008     9
2007     9
2006     8
2013     8
2004     7
2002     5
Name: count, dtype: int64

--- Latest household survey ---
Nombre de valeurs uniques: 60
Top 10 des valeurs les plus fréquentes:
Latest household survey
Multiple Indicator Cluster Survey (MICS), 2012    10
World Health Survey (WHS), 2003                   10
Demographic and Health Survey (DHS), 2013         10
Multiple Indicator Cluster Survey (MICS), 2011     9
Multiple Indicator Cluster Survey (MICS), 2010     9
Demographic and Health Survey (DHS), 2012          8
Demographic and Health Survey (DHS), 2011          6
Demographic and Health Survey (DHS), 2009          4
Demographic and Health Survey (DHS), 2011/12       4
Demographic and Health Survey (DHS), 2010          4
Name: count, dtype: int64

--- Source of most recent Income and expenditure data ---
Nombre de valeurs uniques: 75
Top 10 des valeurs les plus fréquentes:
Source of most recent Income and expenditure data
Integrated household survey (IHS), 2012           15
Integrated household survey (IHS), 2010            9
Integrated household survey (IHS), 2011            9
Expenditure survey/budget survey (ES/BS), 2012     7
Integrated household survey (IHS), 2008            7
Integrated household survey (IHS), 2000            6
Expenditure survey/budget survey (ES/BS), 2009     5
Expenditure survey/budget survey (ES/BS), 2007     4
Expenditure survey/budget survey (ES/BS), 2011     4
Income survey (IS), 2000                           4
Name: count, dtype: int64

--- Latest agricultural census ---
Nombre de valeurs uniques: 35
Top 10 des valeurs les plus fréquentes:
Latest agricultural census
2010                                    36
2007                                    16
2013                                    13
2012                                    10
2011                                     9
2014                                     7
2008                                     5
2009                                     5
2013/ 2014                               4
2010. Population and Housing Census.     3
Name: count, dtype: int64

--- Latest water withdrawal data ---
Nombre de valeurs uniques: 20
Top 10 des valeurs les plus fréquentes:
Latest water withdrawal data
2000    40
2005    40
2007    18
2002    16
2009    12
2006    10
2001    10
2008     6
2003     6
2004     6
Name: count, dtype: int64

==================================================

In [15]:
# ===========================================
# ANALYSE DU FICHIER EdStatsCountry-Series.csv
# ===========================================

print("=" * 50)
print("ANALYSE DE EdStatsCountry-Series.csv")
print("=" * 50)

# Chargement du fichier
df_country_series = pd.read_csv('EdStatsCountry-Series.csv')

# 1. Définition de ce que représente une ligne
print("\n1. DÉFINITION D'UNE LIGNE:")
print("Une ligne représente une combinaison pays-série d'indicateurs.")
print("Chaque ligne = un pays + une série d'indicateur spécifique")

# 2. Affichage des premières lignes pour comprendre la structure
print("\n2. PREMIÈRES LIGNES:")
display(df_country_series.head())

# 3. Calcul du nombre de lignes et colonnes
print(f"\n3. DIMENSIONS:")
print(f"Nombre de lignes: {df_country_series.shape[0]}")
print(f"Nombre de colonnes: {df_country_series.shape[1]}")

# 4. Informations sur les colonnes
print(f"\n4. INFORMATIONS SUR LES COLONNES:")
print(df_country_series.info())

# 5. Calcul du nombre de doublons
print(f"\n5. DOUBLONS:")
nb_doublons = df_country_series.duplicated().sum()
print(f"Nombre de doublons: {nb_doublons}")

if nb_doublons > 0:
    print("Suppression des doublons...")
    df_country_series = df_country_series.drop_duplicates()
    print(f"Nouveau nombre de lignes après suppression: {df_country_series.shape[0]}")
else:
    print("Aucun doublon trouvé.")

# 6. Proportion de valeurs manquantes par colonne
print(f"\n6. VALEURS MANQUANTES PAR COLONNE:")
missing_prop = df_country_series.isnull().sum() / len(df_country_series) * 100
print(missing_prop)

# 7. Identification des colonnes inutilisables (trop de valeurs manquantes)
print(f"\n7. COLONNES INUTILISABLES (plus de 50% de valeurs manquantes):")
colonnes_inutilisables = missing_prop[missing_prop > 50].index.tolist()
print(f"Colonnes à supprimer: {colonnes_inutilisables}")

if colonnes_inutilisables:
    print("Suppression des colonnes inutilisables...")
    df_country_series = df_country_series.drop(columns=colonnes_inutilisables)
    print(f"Nouvelles dimensions: {df_country_series.shape}")

# 8. Statistiques descriptives pour les colonnes numériques
print(f"\n8. STATISTIQUES DESCRIPTIVES (colonnes numériques):")
colonnes_numeriques = df_country_series.select_dtypes(include=['number']).columns
if len(colonnes_numeriques) > 0:
    print(df_country_series[colonnes_numeriques].describe())
else:
    print("Aucune colonne numérique trouvée.")

# 9. Analyse des colonnes catégorielles
print(f"\n9. ANALYSE DES COLONNES CATÉGORIELLES:")
colonnes_categorielles = df_country_series.select_dtypes(include=['object']).columns
for col in colonnes_categorielles:
    print(f"\n--- {col} ---")
    print(f"Nombre de valeurs uniques: {df_country_series[col].nunique()}")
    print("Top 10 des valeurs les plus fréquentes:")
    print(df_country_series[col].value_counts().head(10))

print("\n" + "=" * 50)

==================================================
ANALYSE DE EdStatsCountry-Series.csv
==================================================

1. DÉFINITION D'UNE LIGNE:
Une ligne représente une combinaison pays-série d'indicateurs.
Chaque ligne = un pays + une série d'indicateur spécifique

2. PREMIÈRES LIGNES:

,CountryCode,SeriesCode,DESCRIPTION,Unnamed: 3
0,ABW,SP.POP.TOTL,Data sources : United Nations World Population...,NaN
1,ABW,SP.POP.GROW,Data sources: United Nations World Population ...,NaN
2,AFG,SP.POP.GROW,Data sources: United Nations World Population ...,NaN
3,AFG,NY.GDP.PCAP.PP.CD,Estimates are based on regression.,NaN
4,AFG,SP.POP.TOTL,Data sources : United Nations World Population...,NaN

3. DIMENSIONS:
Nombre de lignes: 613
Nombre de colonnes: 4

4. INFORMATIONS SUR LES COLONNES:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 613 entries, 0 to 612
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CountryCode  613 non-null    object
 1   SeriesCode   613 non-null    object
 2   DESCRIPTION  613 non-null    object
 3   Unnamed: 3   0 non-null      float64
dtypes: float64(1), object(3)
memory usage: 19.3+ KB
None

5. DOUBLONS:
Nombre de doublons: 0
Aucun doublon trouvé.

6. VALEURS MANQUANTES PAR COLONNE:
CountryCode      0.0
SeriesCode       0.0
DESCRIPTION      0.0
Unnamed: 3     100.0
dtype: float64

7. COLONNES INUTILISABLES (plus de 50% de valeurs manquantes):
Colonnes à supprimer: ['Unnamed: 3']
Suppression des colonnes inutilisables...
Nouvelles dimensions: (613, 3)

8. STATISTIQUES DESCRIPTIVES (colonnes numériques):
Aucune colonne numérique trouvée.

9. ANALYSE DES COLONNES CATÉGORIELLES:

--- CountryCode ---
Nombre de valeurs uniques: 211
Top 10 des valeurs les plus fréquentes:
CountryCode
GEO    18
MDA    18
CYP    12
SRB    12
MUS    12
MAR    12
TZA    12
GUY     8
ERI     8
ARG     8
Name: count, dtype: int64

--- SeriesCode ---
Nombre de valeurs uniques: 21
Top 10 des valeurs les plus fréquentes:
SeriesCode
SP.POP.TOTL          211
SP.POP.GROW          211
NY.GDP.PCAP.PP.CD     19
NY.GNP.PCAP.PP.CD     19
NY.GDP.PCAP.PP.KD     19
NY.GNP.MKTP.PP.CD     14
NY.GDP.MKTP.PP.KD     14
NY.GDP.MKTP.PP.CD     14
SP.POP.1564.TO.ZS     13
SP.POP.TOTL.MA.ZS     13
Name: count, dtype: int64

--- DESCRIPTION ---
Nombre de valeurs uniques: 97
Top 10 des valeurs les plus fréquentes:
DESCRIPTION
Data sources : United Nations World Population Prospects                                       154
Data sources: United Nations World Population Prospects                                        137
Estimates are based on regression.                                                              84
Data sources : Eurostat                                                                         54
Derived using ratio of age group from WPP and World Bank population.                            24
Data are for areas under the effective control of the Government of the Republic of Cyprus.      6
Excludes Abkhazia and South Ossetia.                                                             6
Includes Former Spanish Sahara.                                                                  6
Excludes Transnistria.                                                                           6
Covers mainland Tanzania only.                                                                   6
Name: count, dtype: int64

==================================================

In [16]:
# ===========================================
# ANALYSE DU FICHIER EdStatsData.csv
# ===========================================

print("=" * 50)
print("ANALYSE DE EdStatsData.csv")
print("=" * 50)

# Chargement du fichier
df_data = pd.read_csv('EdStatsData.csv')

# 1. Définition de ce que représente une ligne
print("\n1. DÉFINITION D'UNE LIGNE:")
print("Une ligne représente une observation d'un indicateur pour un pays à une année donnée.")
print("Chaque ligne = un pays + un indicateur + une année + une valeur")

# 2. Affichage des premières lignes pour comprendre la structure
print("\n2. PREMIÈRES LIGNES:")
display(df_data.head())

# 3. Calcul du nombre de lignes et colonnes
print(f"\n3. DIMENSIONS:")
print(f"Nombre de lignes: {df_data.shape[0]}")
print(f"Nombre de colonnes: {df_data.shape[1]}")

# 4. Informations sur les colonnes
print(f"\n4. INFORMATIONS SUR LES COLONNES:")
print(df_data.info())

# 5. Calcul du nombre de doublons
print(f"\n5. DOUBLONS:")
nb_doublons = df_data.duplicated().sum()
print(f"Nombre de doublons: {nb_doublons}")

if nb_doublons > 0:
    print("Suppression des doublons...")
    df_data = df_data.drop_duplicates()
    print(f"Nouveau nombre de lignes après suppression: {df_data.shape[0]}")
else:
    print("Aucun doublon trouvé.")

# 6. Proportion de valeurs manquantes par colonne
print(f"\n6. VALEURS MANQUANTES PAR COLONNE:")
missing_prop = df_data.isnull().sum() / len(df_data) * 100
print(missing_prop)

# 7. Identification des colonnes inutilisables (trop de valeurs manquantes)
print(f"\n7. COLONNES INUTILISABLES (plus de 50% de valeurs manquantes):")
colonnes_inutilisables = missing_prop[missing_prop > 50].index.tolist()
print(f"Colonnes à supprimer: {colonnes_inutilisables}")

if colonnes_inutilisables:
    print("Suppression des colonnes inutilisables...")
    df_data = df_data.drop(columns=colonnes_inutilisables)
    print(f"Nouvelles dimensions: {df_data.shape}")

# 8. Statistiques descriptives pour les colonnes numériques
print(f"\n8. STATISTIQUES DESCRIPTIVES (colonnes numériques):")
colonnes_numeriques = df_data.select_dtypes(include=['number']).columns
if len(colonnes_numeriques) > 0:
    print(df_data[colonnes_numeriques].describe())
else:
    print("Aucune colonne numérique trouvée.")

# 9. Analyse des colonnes catégorielles
print(f"\n9. ANALYSE DES COLONNES CATÉGORIELLES:")
colonnes_categorielles = df_data.select_dtypes(include=['object']).columns
for col in colonnes_categorielles:
    print(f"\n--- {col} ---")
    print(f"Nombre de valeurs uniques: {df_data[col].nunique()}")
    print("Top 10 des valeurs les plus fréquentes:")
    print(df_data[col].value_counts().head(10))

print("\n" + "=" * 50)

==================================================
ANALYSE DE EdStatsData.csv
==================================================

1. DÉFINITION D'UNE LIGNE:
Une ligne représente une observation d'un indicateur pour un pays à une année donnée.
Chaque ligne = un pays + un indicateur + une année + une valeur

2. PREMIÈRES LIGNES:

,Country Name,Country Code,Indicator Name,Indicator Code,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2020,2025,2030,2035,2040,2045,2050,2055,2060,2065,2070,2075,2080,2085,2090,2095,2100,Unnamed: 69
0,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.GPI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Arab World,ARB,"Adjusted net enrolment rate, primary, both sex...",SE.PRM.TENR,54.822121,54.894138,56.209438,57.267109,57.991138,59.36554,60.999962,61.92268,62.69342,64.383186,65.617767,66.085152,66.608139,67.290451,68.510094,69.033211,69.944908,71.04187,71.693779,71.699097,71.995819,72.602837,70.032722,70.464821,72.645683,71.81176,73.903511,74.425201,75.110817,76.254318,77.245682,78.800522,80.051399,80.805389,81.607063,82.489487,82.685509,83.280342,84.011871,84.195961,85.211998,85.24514,86.101669,85.51194,85.320152,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

3. DIMENSIONS:
Nombre de lignes: 886930
Nombre de colonnes: 70

4. INFORMATIONS SUR LES COLONNES:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 886930 entries, 0 to 886929
Data columns (total 70 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Country Name    886930 non-null  object
 1   Country Code    886930 non-null  object
 2   Indicator Name  886930 non-null  object
 3   Indicator Code  886930 non-null  object
 4   1970            72288 non-null   float64
 5   1971            35537 non-null   float64
 6   1972            35619 non-null   float64
 7   1973            35545 non-null   float64
 8   1974            35730 non-null   float64
 9   1975            87306 non-null   float64
 10  1976            37483 non-null   float64
 11  1977            37574 non-null   float64
 12  1978            37576 non-null   float64
 13  1979            36809 non-null   float64
 14  1980            89122 non-null   float64
 15  1981            38777 non-null   float64
 16  1982            37511 non-null   float64
 17  1983            38460 non-null   float64
 18  1984            38606 non-null   float64
 19  1985            90296 non-null   float64
 20  1986            39372 non-null   float64
 21  1987            38641 non-null   float64
 22  1988            38552 non-null   float64
 23  1989            37540 non-null   float64
 24  1990            124405 non-null  float64
 25  1991            74437 non-null   float64
 26  1992            75543 non-null   float64
 27  1993            75793 non-null   float64
 28  1994            77462 non-null   float64
 29  1995            131361 non-null  float64
 30  1996            76807 non-null   float64
 31  1997            73453 non-null   float64
 32  1998            84914 non-null   float64
 33  1999            118839 non-null  float64
 34  2000            176676 non-null  float64
 35  2001            123509 non-null  float64
 36  2002            124205 non-null  float64
 37  2003            130363 non-null  float64
 38  2004            128814 non-null  float64
 39  2005            184108 non-null  float64
 40  2006            140312 non-null  float64
 41  2007            137272 non-null  float64
 42  2008            134387 non-null  float64
 43  2009            142108 non-null  float64
 44  2010            242442 non-null  float64
 45  2011            146012 non-null  float64
 46  2012            147264 non-null  float64
 47  2013            137509 non-null  float64
 48  2014            113789 non-null  float64
 49  2015            131058 non-null  float64
 50  2016            16460 non-null   float64
 51  2017            143 non-null     float64
 52  2020            51436 non-null   float64
 53  2025            51436 non-null   float64
 54  2030            51436 non-null   float64
 55  2035            51436 non-null   float64
 56  2040            51436 non-null   float64
 57  2045            51436 non-null   float64
 58  2050            51436 non-null   float64
 59  2055            51436 non-null   float64
 60  2060            51436 non-null   float64
 61  2065            51436 non-null   float64
 62  2070            51436 non-null   float64
 63  2075            51436 non-null   float64
 64  2080            51436 non-null   float64
 65  2085            51436 non-null   float64
 66  2090            51436 non-null   float64
 67  2095            51436 non-null   float64
 68  2100            51436 non-null   float64
 69  Unnamed: 69     0 non-null       float64
dtypes: float64(66), object(4)
memory usage: 473.7+ MB
None

5. DOUBLONS:
Nombre de doublons: 0
Aucun doublon trouvé.

6. VALEURS MANQUANTES PAR COLONNE:
Country Name        0.000000
Country Code        0.000000
Indicator Name      0.000000
Indicator Code      0.000000
1970               91.849639
                     ...
2085               94.200670
2090               94.200670
2095               94.200670
2100               94.200670
Unnamed: 69       100.000000
Length: 70, dtype: float64

7. COLONNES INUTILISABLES (plus de 50% de valeurs manquantes):
Colonnes à supprimer: ['1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2020', '2025', '2030', '2035', '2040', '2045', '2050', '2055', '2060', '2065', '2070', '2075', '2080', '2085', '2090', '2095', '2100', 'Unnamed: 69']
Suppression des colonnes inutilisables...
Nouvelles dimensions: (886930, 4)

8. STATISTIQUES DESCRIPTIVES (colonnes numériques):
Aucune colonne numérique trouvée.

9. ANALYSE DES COLONNES CATÉGORIELLES:

--- Country Name ---
Nombre de valeurs uniques: 242
Top 10 des valeurs les plus fréquentes:
Country Name
Arab World                                       3665
East Asia & Pacific                              3665
East Asia & Pacific (excluding high income)      3665
Euro area                                        3665
Europe & Central Asia                            3665
Europe & Central Asia (excluding high income)    3665
European Union                                   3665
Heavily indebted poor countries (HIPC)           3665
High income                                      3665
Latin America & Caribbean                        3665
Name: count, dtype: int64

--- Country Code ---
Nombre de valeurs uniques: 242
Top 10 des valeurs les plus fréquentes:
Country Code
ARB    3665
EAS    3665
EAP    3665
EMU    3665
ECS    3665
ECA    3665
EUU    3665
HPC    3665
HIC    3665
LCN    3665
Name: count, dtype: int64

--- Indicator Name ---
Nombre de valeurs uniques: 3665
Top 10 des valeurs les plus fréquentes:
Indicator Name
Adjusted net enrolment rate, lower secondary, both sexes (%)               242
Adjusted net enrolment rate, lower secondary, female (%)                   242
Adjusted net enrolment rate, lower secondary, gender parity index (GPI)    242
Adjusted net enrolment rate, lower secondary, male (%)                     242
Adjusted net enrolment rate, primary, both sexes (%)                       242
Adjusted net enrolment rate, primary, female (%)                           242
Adjusted net enrolment rate, primary, gender parity index (GPI)            242
Adjusted net enrolment rate, primary, male (%)                             242
Adjusted net enrolment rate, upper secondary, both sexes (%)               242
Adjusted net enrolment rate, upper secondary, female (%)                   242
Name: count, dtype: int64

--- Indicator Code ---
Nombre de valeurs uniques: 3665
Top 10 des valeurs les plus fréquentes:
Indicator Code
UIS.NERA.2        242
UIS.NERA.2.F      242
UIS.NERA.2.GPI    242
UIS.NERA.2.M      242
SE.PRM.TENR       242
SE.PRM.TENR.FE    242
UIS.NERA.1.GPI    242
SE.PRM.TENR.MA    242
UIS.NERA.3        242
UIS.NERA.3.F      242
Name: count, dtype: int64

==================================================

In [17]:
# ===========================================
# ANALYSE DU FICHIER EdStatsFootNote.csv
# ===========================================

print("=" * 50)
print("ANALYSE DE EdStatsFootNote.csv")
print("=" * 50)

# Chargement du fichier
df_footnote = pd.read_csv('EdStatsFootNote.csv')

# 1. Définition de ce que représente une ligne
print("\n1. DÉFINITION D'UNE LIGNE:")
print("Une ligne représente une note de bas de page associée à une donnée spécifique.")
print("Chaque ligne = une note explicative pour une observation particulière")

# 2. Affichage des premières lignes pour comprendre la structure
print("\n2. PREMIÈRES LIGNES:")
display(df_footnote.head())

# 3. Calcul du nombre de lignes et colonnes
print(f"\n3. DIMENSIONS:")
print(f"Nombre de lignes: {df_footnote.shape[0]}")
print(f"Nombre de colonnes: {df_footnote.shape[1]}")

# 4. Informations sur les colonnes
print(f"\n4. INFORMATIONS SUR LES COLONNES:")
print(df_footnote.info())

# 5. Calcul du nombre de doublons
print(f"\n5. DOUBLONS:")
nb_doublons = df_footnote.duplicated().sum()
print(f"Nombre de doublons: {nb_doublons}")

if nb_doublons > 0:
    print("Suppression des doublons...")
    df_footnote = df_footnote.drop_duplicates()
    print(f"Nouveau nombre de lignes après suppression: {df_footnote.shape[0]}")
else:
    print("Aucun doublon trouvé.")

# 6. Proportion de valeurs manquantes par colonne
print(f"\n6. VALEURS MANQUANTES PAR COLONNE:")
missing_prop = df_footnote.isnull().sum() / len(df_footnote) * 100
print(missing_prop)

# 7. Identification des colonnes inutilisables (trop de valeurs manquantes)
print(f"\n7. COLONNES INUTILISABLES (plus de 50% de valeurs manquantes):")
colonnes_inutilisables = missing_prop[missing_prop > 50].index.tolist()
print(f"Colonnes à supprimer: {colonnes_inutilisables}")

if colonnes_inutilisables:
    print("Suppression des colonnes inutilisables...")
    df_footnote = df_footnote.drop(columns=colonnes_inutilisables)
    print(f"Nouvelles dimensions: {df_footnote.shape}")

# 8. Statistiques descriptives pour les colonnes numériques
print(f"\n8. STATISTIQUES DESCRIPTIVES (colonnes numériques):")
colonnes_numeriques = df_footnote.select_dtypes(include=['number']).columns
if len(colonnes_numeriques) > 0:
    print(df_footnote[colonnes_numeriques].describe())
else:
    print("Aucune colonne numérique trouvée.")

# 9. Analyse des colonnes catégorielles
print(f"\n9. ANALYSE DES COLONNES CATÉGORIELLES:")
colonnes_categorielles = df_footnote.select_dtypes(include=['object']).columns
for col in colonnes_categorielles:
    print(f"\n--- {col} ---")
    print(f"Nombre de valeurs uniques: {df_footnote[col].nunique()}")
    print("Top 10 des valeurs les plus fréquentes:")
    print(df_footnote[col].value_counts().head(10))

print("\n" + "=" * 50)

==================================================
ANALYSE DE EdStatsFootNote.csv
==================================================

1. DÉFINITION D'UNE LIGNE:
Une ligne représente une note de bas de page associée à une donnée spécifique.
Chaque ligne = une note explicative pour une observation particulière

2. PREMIÈRES LIGNES:

  CountryCode      SeriesCode    Year          DESCRIPTION  Unnamed: 4
0         ABW  SE.PRE.ENRL.FE  YR2001  Country estimation.         NaN
1         ABW  SE.TER.TCHR.FE  YR2005  Country estimation.         NaN
2         ABW  SE.PRE.TCHR.FE  YR2000  Country estimation.         NaN
3         ABW  SE.SEC.ENRL.GC  YR2004  Country estimation.         NaN
4         ABW     SE.PRE.TCHR  YR2006  Country estimation.         NaN

3. DIMENSIONS:
Nombre de lignes: 643638
Nombre de colonnes: 5

4. INFORMATIONS SUR LES COLONNES:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 643638 entries, 0 to 643637
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   CountryCode  643638 non-null  object
 1   SeriesCode   643638 non-null  object
 2   Year         643638 non-null  object
 3   DESCRIPTION  643638 non-null  object
 4   Unnamed: 4   0 non-null       float64
dtypes: float64(1), object(4)
memory usage: 24.6+ MB
None

5. DOUBLONS:
Nombre de doublons: 0
Aucun doublon trouvé.

6. VALEURS MANQUANTES PAR COLONNE:
CountryCode      0.0
SeriesCode       0.0
Year             0.0
DESCRIPTION      0.0
Unnamed: 4     100.0
dtype: float64

7. COLONNES INUTILISABLES (plus de 50% de valeurs manquantes):
Colonnes à supprimer: ['Unnamed: 4']
Suppression des colonnes inutilisables...
Nouvelles dimensions: (643638, 4)

8. STATISTIQUES DESCRIPTIVES (colonnes numériques):
Aucune colonne numérique trouvée.

9. ANALYSE DES COLONNES CATÉGORIELLES:

--- CountryCode ---
Nombre de valeurs uniques: 239
Top 10 des valeurs les plus fréquentes:
CountryCode
LIC    7320
CYP    7183
LDC    6481
SSA    6389
SSF    6336
HPC    6237
LAC    6116
MIC    5862
LMY    5839
LCN    5779
Name: count, dtype: int64

--- SeriesCode ---
Nombre de valeurs uniques: 1558
Top 10 des valeurs les plus fréquentes:
SeriesCode
SH.DYN.MORT          9226
SE.PRM.AGES          8771
SE.PRM.DURS          8771
SE.SEC.DURS          8619
SE.SEC.AGES          8581
SE.PRM.ENRL          6610
SE.PRM.ENRR          6418
SE.PRM.ENRL.FE.ZS    6177
SE.PRM.ENRL.FE       6165
SE.ENR.PRIM.FM.ZS    6013
Name: count, dtype: int64

--- Year ---
Nombre de valeurs uniques: 56
Top 10 des valeurs les plus fréquentes:
Year
YR2004    27128
YR2005    25992
YR2002    25687
YR2003    25683
YR2000    25093
YR2001    25047
YR2008    25018
YR1999    24938
YR2007    24263
YR2006    23394
Name: count, dtype: int64

--- DESCRIPTION ---
Nombre de valeurs uniques: 9102
Top 10 des valeurs les plus fréquentes:
DESCRIPTION
Country Data                                      191188
UNESCO Institute for Statistics (UIS) estimate    171527
Estimated                                         117155
UIS Estimation                                     31395
Country estimation.                                26308
National Estimate                                  23570
Country data                                       16353
National Estimation                                12001
UNSD WPP08 revision file 2A and 3A.                 3480
Reference Period: 2005-2014.                        3406
Name: count, dtype: int64

==================================================

In [18]:
# ===========================================
# ANALYSE DU FICHIER EdStatsSeries.csv
# ===========================================

print("=" * 50)
print("ANALYSE DE EdStatsSeries.csv")
print("=" * 50)

# Chargement du fichier
df_series = pd.read_csv('EdStatsSeries.csv')

# 1. Définition de ce que représente une ligne
print("\n1. DÉFINITION D'UNE LIGNE:")
print("Une ligne représente un indicateur/série statistique avec ses métadonnées.")
print("Chaque ligne = un indicateur unique avec ses caractéristiques")

# 2. Affichage des premières lignes pour comprendre la structure
print("\n2. PREMIÈRES LIGNES:")
display(df_series.head())

# 3. Calcul du nombre de lignes et colonnes
print(f"\n3. DIMENSIONS:")
print(f"Nombre de lignes: {df_series.shape[0]}")
print(f"Nombre de colonnes: {df_series.shape[1]}")

# 4. Informations sur les colonnes
print(f"\n4. INFORMATIONS SUR LES COLONNES:")
print(df_series.info())

# 5. Calcul du nombre de doublons
print(f"\n5. DOUBLONS:")
nb_doublons = df_series.duplicated().sum()
print(f"Nombre de doublons: {nb_doublons}")

if nb_doublons > 0:
    print("Suppression des doublons...")
    df_series = df_series.drop_duplicates()
    print(f"Nouveau nombre de lignes après suppression: {df_series.shape[0]}")
else:
    print("Aucun doublon trouvé.")

# 6. Proportion de valeurs manquantes par colonne
print(f"\n6. VALEURS MANQUANTES PAR COLONNE:")
missing_prop = df_series.isnull().sum() / len(df_series) * 100
print(missing_prop)

# 7. Identification des colonnes inutilisables (trop de valeurs manquantes)
print(f"\n7. COLONNES INUTILISABLES (plus de 50% de valeurs manquantes):")
colonnes_inutilisables = missing_prop[missing_prop > 50].index.tolist()
print(f"Colonnes à supprimer: {colonnes_inutilisables}")

if colonnes_inutilisables:
    print("Suppression des colonnes inutilisables...")
    df_series = df_series.drop(columns=colonnes_inutilisables)
    print(f"Nouvelles dimensions: {df_series.shape}")

# 8. Statistiques descriptives pour les colonnes numériques
print(f"\n8. STATISTIQUES DESCRIPTIVES (colonnes numériques):")
colonnes_numeriques = df_series.select_dtypes(include=['number']).columns
if len(colonnes_numeriques) > 0:
    print(df_series[colonnes_numeriques].describe())
else:
    print("Aucune colonne numérique trouvée.")

# 9. Analyse des colonnes catégorielles
print(f"\n9. ANALYSE DES COLONNES CATÉGORIELLES:")
colonnes_categorielles = df_series.select_dtypes(include=['object']).columns
for col in colonnes_categorielles:
    print(f"\n--- {col} ---")
    print(f"Nombre de valeurs uniques: {df_series[col].nunique()}")
    print("Top 10 des valeurs les plus fréquentes:")
    print(df_series[col].value_counts().head(10))

print("\n" + "=" * 50)

==================================================
ANALYSE DE EdStatsSeries.csv
==================================================

1. DÉFINITION D'UNE LIGNE:
Une ligne représente un indicateur/série statistique avec ses métadonnées.
Chaque ligne = un indicateur unique avec ses caractéristiques

2. PREMIÈRES LIGNES:

,Series Code,Topic,Indicator Name,Short definition,Long definition,Unit of measure,Periodicity,Base Period,Other notes,Aggregation method,Limitations and exceptions,Notes from original source,General comments,Source,Statistical concept and methodology,Development relevance,Related source links,Other web links,Related indicators,License Type,Unnamed: 20
0,BAR.NOED.1519.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 15-19 with...,Percentage of female population age 15-19 with...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Robert J. Barro and Jong-Wha Lee: http://www.b...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BAR.NOED.1519.ZS,Attainment,Barro-Lee: Percentage of population age 15-19 ...,Percentage of population age 15-19 with no edu...,Percentage of population age 15-19 with no edu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Robert J. Barro and Jong-Wha Lee: http://www.b...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BAR.NOED.15UP.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 15+ with n...,Percentage of female population age 15+ with n...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Robert J. Barro and Jong-Wha Lee: http://www.b...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BAR.NOED.15UP.ZS,Attainment,Barro-Lee: Percentage of population age 15+ wi...,Percentage of population age 15+ with no educa...,Percentage of population age 15+ with no educa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Robert J. Barro and Jong-Wha Lee: http://www.b...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BAR.NOED.2024.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 20-24 with...,Percentage of female population age 20-24 with...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Robert J. Barro and Jong-Wha Lee: http://www.b...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

3. DIMENSIONS:
Nombre de lignes: 3665
Nombre de colonnes: 21

4. INFORMATIONS SUR LES COLONNES:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3665 entries, 0 to 3664
Data columns (total 21 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Series Code                          3665 non-null   object
 1   Topic                                3665 non-null   object
 2   Indicator Name                       3665 non-null   object
 3   Short definition                     2156 non-null   object
 4   Long definition                      3665 non-null   object
 5   Unit of measure                      0 non-null      float64
 6   Periodicity                          99 non-null     object
 7   Base Period                          314 non-null    object
 8   Other notes                          552 non-null    object
 9   Aggregation method                   47 non-null     object
 10  Limitations and exceptions           14 non-null     object
 11  Notes from original source           0 non-null      float64
 12  General comments                     14 non-null     object
 13  Source                               3665 non-null   object
 14  Statistical concept and methodology  23 non-null     object
 15  Development relevance                3 non-null      object
 16  Related source links                 215 non-null    object
 17  Other web links                      0 non-null      float64
 18  Related indicators                   0 non-null      float64
 19  License Type                         0 non-null      float64
 20  Unnamed: 20                          0 non-null      float64
dtypes: float64(6), object(15)
memory usage: 601.4+ KB
None

5. DOUBLONS:
Nombre de doublons: 0
Aucun doublon trouvé.

6. VALEURS MANQUANTES PAR COLONNE:
Series Code                              0.000000
Topic                                    0.000000
Indicator Name                           0.000000
Short definition                        41.173261
Long definition                          0.000000
Unit of measure                        100.000000
Periodicity                             97.298772
Base Period                             91.432469
Other notes                             84.938608
Aggregation method                      98.717599
Limitations and exceptions              99.618008
Notes from original source             100.000000
General comments                        99.618008
Source                                   0.000000
Statistical concept and methodology     99.372442
Development relevance                   99.918145
Related source links                    94.133697
Other web links                        100.000000
Related indicators                     100.000000
License Type                           100.000000
Unnamed: 20                            100.000000
dtype: float64

7. COLONNES INUTILISABLES (plus de 50% de valeurs manquantes):
Colonnes à supprimer: ['Unit of measure', 'Periodicity', 'Base Period', 'Other notes', 'Aggregation method', 'Limitations and exceptions', 'Notes from original source', 'General comments', 'Statistical concept and methodology', 'Development relevance', 'Related source links', 'Other web links', 'Related indicators', 'License Type', 'Unnamed: 20']
Suppression des colonnes inutilisables...
Nouvelles dimensions: (3665, 6)

8. STATISTIQUES DESCRIPTIVES (colonnes numériques):
Aucune colonne numérique trouvée.

9. ANALYSE DES COLONNES CATÉGORIELLES:

--- Series Code ---
Nombre de valeurs uniques: 3665
Top 10 des valeurs les plus fréquentes:
Series Code
BAR.NOED.1519.FE.ZS    1
BAR.NOED.1519.ZS       1
BAR.NOED.15UP.FE.ZS    1
BAR.NOED.15UP.ZS       1
BAR.NOED.2024.FE.ZS    1
BAR.NOED.2024.ZS       1
BAR.NOED.2529.FE.ZS    1
BAR.NOED.2529.ZS       1
BAR.NOED.25UP.FE.ZS    1
BAR.NOED.25UP.ZS       1
Name: count, dtype: int64

--- Topic ---
Nombre de valeurs uniques: 37
Top 10 des valeurs les plus fréquentes:
Topic
Learning Outcomes                      1046
Attainment                              733
Education Equality                      426
Secondary                               256
Primary                                 248
Population                              213
Tertiary                                158
Teachers                                137
Expenditures                             93
Engaging the Private Sector (SABER)      51
Name: count, dtype: int64

--- Indicator Name ---
Nombre de valeurs uniques: 3665
Top 10 des valeurs les plus fréquentes:
Indicator Name
Barro-Lee: Percentage of female population age 15-19 with no education    1
Barro-Lee: Percentage of population age 15-19 with no education           1
Barro-Lee: Percentage of female population age 15+ with no education      1
Barro-Lee: Percentage of population age 15+ with no education             1
Barro-Lee: Percentage of female population age 20-24 with no education    1
Barro-Lee: Percentage of population age 20-24 with no education           1
Barro-Lee: Percentage of female population age 25-29 with no education    1
Barro-Lee: Percentage of population age 25-29 with no education           1
Barro-Lee: Percentage of female population age 25+ with no education      1
Barro-Lee: Percentage of population age 25+ with no education             1
Name: count, dtype: int64

--- Short definition ---
Nombre de valeurs uniques: 1169
Top 10 des valeurs les plus fréquentes:
Short definition
Data Interpretation: 1=Latent; 2=Emerging; 3=Established; 4=Advanced. For additional information, visit the SABER: (website: http://saber.worldbank.org/index.cfm                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     215
Average total number of invented/nonsense words correctly read per minute. The indicator measures students' ability to fluently decipher/decode randomly-presented “words” that follow linguistic rules but do not actually exist in the stated language. Skill in reading nonwords can be a purer measure of decoding than using real words because children cannot recognize the words by sight. Decoding is considered a self-teaching skill that enables children to read new and unfamiliar words independently. Users are discouraged from using these data to make direct comparisons across countries or languages. Consult the EdData website and the specific country report for more information: www.eddataglobal.org.     51
Share of students who scored zero percent on the reading comprehension assessment. The reading comprehension subtask follows the oral reading fluency subtask; students are required to respond to literal and inferential questions about the oral reading fluency subtask text they have just read. The questions are read aloud to the student by the assessor. Consult the EdData website and the specific country report for more information: www.eddataglobal.org.                                                                                                                                                                                                                                                              51
Share of students who scored 80 percent or higher on the reading comprehension assessment. The reading comprehension subtask follows the oral reading fluency subtask; students are required to respond to literal and inferential questions about the oral reading fluency subtask text they have just read. The questions are read aloud to the student by the assessor. Users are discouraged from using these data to make direct comparisons across countries or languages. Consult the EdData website and the specific country report for more information: www.eddataglobal.org.                                                                                                                                                51
Percentage of students who were unable to read a single word of text on the oral reading fluency subtask. The oral reading fluency/paragraph reading subtask examines students' ability to read a narrative or informational text with accuracy, with little effort, and at a sufficient rate. Consult the EdData website and the specific country report for more information: www.eddataglobal.org.                                                                                                                                                                                                                                                                                                                                  51
Share of students scoring zero percent on the listening comprehension assessment. The listening comprehension subtask examines students' ability to respond correctly to questions about a brief passage read aloud to the student by the assessor in order to understand students’ ability to comprehend orally without having to overcome issues of decoding. Part of comprehension is understanding the meanings of the words, thus if students do not have enough vocabulary in the language, they will not be able to comprehend. Consult the EdData website and the specific country report for more information: www.eddataglobal.org.                                                                                          50
Average total number of words correctly read per minute from a narrative or informational reading passage. The oral reading fluency/paragraph reading subtask examines students' ability to read a narrative or informational text with accuracy, with little effort, and at a sufficient rate. Assessors ask students to read the paragraph and stop them after one minute to record the number of words correctly read. Users are discouraged from using these data to make direct comparisons across countries or languages. Consult the EdData website and the specific country report for more information: www.eddataglobal.org .                                                                                                32
Average total number of familiar words correctly read per minute. The familiar word reading subtask tests students' ability to read a list of one or two syllable words drawn from a corpus of frequent words presented in random order. Users are discouraged from using these data to make direct comparisons across countries or languages. Consult the EdData website and the specific country report for more information: www.eddataglobal.org.                                                                                                                                                                                                                                                                                  30
Average number of letter sounds that students could read per minute. In this EGRA subtask, assessors present students with a sheet listing between 50 and 100 upper- and lowercase letters of the alphabet (in some languages, graphemes, or sets of letters and/or symbols representing a single sound, are presented). Students are asked to provide the sounds of all the letters that they can in one minute. Users are discouraged from using these data to make direct comparisons across countries or languages. Consult the EdData website and the specific country report for more information: www.eddataglobal.org.                                                                                                         28
Average number of letter names that students could read per minute. In this EGRA subtask, assessors present students with a sheet listing between 50 and 100 upper- and lowercase letters of the alphabet (in some languages, graphemes, or sets of letters and/or symbols representing a single sound, are presented). Students are asked to provide the names of all the letters that they can in one minute. Users are discouraged from using these data to make direct comparisons across countries or languages. Consult the EdData website and the specific country report for more information: www.eddataglobal.org.                                                                                                           25
Name: count, dtype: int64

--- Long definition ---
Nombre de valeurs uniques: 2060
Top 10 des valeurs les plus fréquentes:
Long definition
Data Interpretation: 1=Latent; 2=Emerging; 3=Established; 4=Advanced. For additional information, visit the SABER: (website: http://saber.worldbank.org/index.cfm                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     215
Average total number of invented/nonsense words correctly read per minute. The indicator measures students' ability to fluently decipher/decode randomly-presented “words” that follow linguistic rules but do not actually exist in the stated language. Skill in reading nonwords can be a purer measure of decoding than using real words because children cannot recognize the words by sight. Decoding is considered a self-teaching skill that enables children to read new and unfamiliar words independently. Users are discouraged from using these data to make direct comparisons across countries or languages. Consult the EdData website and the specific country report for more information: www.eddataglobal.org.     51
Share of students who scored 80 percent or higher on the reading comprehension assessment. The reading comprehension subtask follows the oral reading fluency subtask; students are required to respond to literal and inferential questions about the oral reading fluency subtask text they have just read. The questions are read aloud to the student by the assessor. Users are discouraged from using these data to make direct comparisons across countries or languages. Consult the EdData website and the specific country report for more information: www.eddataglobal.org.                                                                                                                                                51
Share of students who scored zero percent on the reading comprehension assessment. The reading comprehension subtask follows the oral reading fluency subtask; students are required to respond to literal and inferential questions about the oral reading fluency subtask text they have just read. The questions are read aloud to the student by the assessor. Consult the EdData website and the specific country report for more information: www.eddataglobal.org.                                                                                                                                                                                                                                                              51
Percentage of students who were unable to read a single word of text on the oral reading fluency subtask. The oral reading fluency/paragraph reading subtask examines students' ability to read a narrative or informational text with accuracy, with little effort, and at a sufficient rate. Consult the EdData website and the specific country report for more information: www.eddataglobal.org.                                                                                                                                                                                                                                                                                                                                  51
Share of students scoring zero percent on the listening comprehension assessment. The listening comprehension subtask examines students' ability to respond correctly to questions about a brief passage read aloud to the student by the assessor in order to understand students’ ability to comprehend orally without having to overcome issues of decoding. Part of comprehension is understanding the meanings of the words, thus if students do not have enough vocabulary in the language, they will not be able to comprehend. Consult the EdData website and the specific country report for more information: www.eddataglobal.org.                                                                                          50
Mean number of years spent in school by age group and gender. Projections are based on collected census and survey data for the base year (around 2010) and the Medium Shared Socioeconomic Pathways (SSP2) projection model. The SSP2 is a middle-of-the-road scenario that combines medium fertility with medium mortality, medium migration, and the Global Education Trend (GET) education scenario. For more information and other projection models, consult the Wittgenstein Centre for Demography and Global Human Capital's website: http://www.oeaw.ac.at/vid/dataexplorer/                                                                                                                                                  36
Share of the population of the stated age group that has completed post-secondary or tertiary education as the highest level of educational attainment. Projections are based on collected census and survey data for the base year (around 2010) and the Medium Shared Socioeconomic Pathways (SSP2) projection model. The SSP2 is a middle-of-the-road scenario that combines medium fertility with medium mortality, medium migration, and the Global Education Trend (GET) education scenario. For more information and other projection models, consult the Wittgenstein Centre for Demography and Global Human Capital's website: http://www.oeaw.ac.at/vid/dataexplorer/                                                        33
Share of the population of the stated age group that has completed lower secondary or incomplete upper secondary education as the highest level of educational attainment. Projections are based on collected census and survey data for the base year (around 2010) and the Medium Shared Socioeconomic Pathways (SSP2) projection model. The SSP2 is a middle-of-the-road scenario that combines medium fertility with medium mortality, medium migration, and the Global Education Trend (GET) education scenario. For more information and other projection models, consult the Wittgenstein Centre for Demography and Global Human Capital's website: http://www.oeaw.ac.at/vid/dataexplorer/                                     33
Share of the population of the stated age group that has completed primary education or incomplete lower secondary education as the highest level of educational attainment. Projections are based on collected census and survey data for the base year (around 2010) and the Medium Shared Socioeconomic Pathways (SSP2) projection model. The SSP2 is a middle-of-the-road scenario that combines medium fertility with medium mortality, medium migration, and the Global Education Trend (GET) education scenario. For more information and other projection models, consult the Wittgenstein Centre for Demography and Global Human Capital's website: http://www.oeaw.ac.at/vid/dataexplorer/                                   33
Name: count, dtype: int64

--- Source ---
Nombre de valeurs uniques: 31

In [19]:
# ===========================================
# SYNTHÈSE DE L'ANALYSE DE TOUS LES FICHIERS
# ===========================================

print("=" * 60)
print("SYNTHÈSE DE L'ANALYSE DE TOUS LES FICHIERS")
print("=" * 60)

# Création d'un DataFrame de synthèse
synthese = {
    'Fichier': ['EdStatsCountry.csv', 'EdStatsCountry-Series.csv', 'EdStatsData.csv', 'EdStatsFootNote.csv', 'EdStatsSeries.csv'],
    'DataFrame': [df_country, df_country_series, df_data, df_footnote, df_series],
    'Description_ligne': [
        'Un pays avec ses informations géographiques et économiques',
        'Une combinaison pays-série d\'indicateurs',
        'Une observation d\'un indicateur pour un pays à une année donnée',
        'Une note de bas de page associée à une donnée spécifique',
        'Un indicateur/série statistique avec ses métadonnées'
    ]
}

print("\nRÉSUMÉ DES DIMENSIONS ET CARACTÉRISTIQUES:")
print("-" * 60)

for i, (fichier, df, desc) in enumerate(zip(synthese['Fichier'], synthese['DataFrame'], synthese['Description_ligne'])):
    print(f"\n{i+1}. {fichier}")
    print(f"   Description d'une ligne: {desc}")
    print(f"   Dimensions: {df.shape[0]} lignes × {df.shape[1]} colonnes")
    print(f"   Doublons: {df.duplicated().sum()}")
    
    # Calcul des valeurs manquantes
    missing_prop = df.isnull().sum() / len(df) * 100
    colonnes_avec_manquants = missing_prop[missing_prop > 0]
    print(f"   Colonnes avec valeurs manquantes: {len(colonnes_avec_manquants)}")
    
    # Types de colonnes
    numeriques = len(df.select_dtypes(include=['number']).columns)
    categorielles = len(df.select_dtypes(include=['object']).columns)
    print(f"   Colonnes numériques: {numeriques}")
    print(f"   Colonnes catégorielles: {categorielles}")

print("\n" + "=" * 60)
print("ANALYSE TERMINÉE - Tous les fichiers ont été traités selon les instructions")
print("=" * 60)

============================================================
SYNTHÈSE DE L'ANALYSE DE TOUS LES FICHIERS
============================================================

RÉSUMÉ DES DIMENSIONS ET CARACTÉRISTIQUES:
------------------------------------------------------------

1. EdStatsCountry.csv
   Description d'une ligne: Un pays avec ses informations géographiques et économiques
   Dimensions: 241 lignes × 26 colonnes
   Doublons: 0
   Colonnes avec valeurs manquantes: 22
   Colonnes numériques: 1
   Colonnes catégorielles: 25

2. EdStatsCountry-Series.csv
   Description d'une ligne: Une combinaison pays-série d'indicateurs
   Dimensions: 613 lignes × 3 colonnes
   Doublons: 0
   Colonnes avec valeurs manquantes: 0
   Colonnes numériques: 0
   Colonnes catégorielles: 3

3. EdStatsData.csv
   Description d'une ligne: Une observation d'un indicateur pour un pays à une année donnée
   Dimensions: 886930 lignes × 4 colonnes
   Doublons: 0
   Colonnes avec valeurs manquantes: 0
   Colonnes numériques: 0
   Colonnes catégorielles: 4

4. EdStatsFootNote.csv
   Description d'une ligne: Une note de bas de page associée à une donnée spécifique
   Dimensions: 643638 lignes × 4 colonnes
   Doublons: 0
   Colonnes avec valeurs manquantes: 0
   Colonnes numériques: 0
   Colonnes catégorielles: 4

5. EdStatsSeries.csv
   Description d'une ligne: Un indicateur/série statistique avec ses métadonnées
   Dimensions: 3665 lignes × 6 colonnes
   Doublons: 0
   Colonnes avec valeurs manquantes: 1
   Colonnes numériques: 0
   Colonnes catégorielles: 6

============================================================
ANALYSE TERMINÉE - Tous les fichiers ont été traités selon les instructions
============================================================

In [20]:
# --- Chargement du fichier ---
# Assurez-vous que le fichier EdStatsCountry.csv est dans le même dossier que votre notebook
df_country = pd.read_csv('EdStatsCountry.csv')

# --- Identification des faux pays ---
# On sélectionne les lignes où la colonne 'Region' est vide (.isnull())
faux_pays_df = df_country[df_country['Region'].isnull()]
print("--- Faux pays identifiés (lignes sans information de Région) ---")
# On affiche quelques colonnes pour vérifier
print(faux_pays_df[['Country Code', 'Short Name', 'Income Group']])

# --- Création de la liste des codes à exclure ---
faux_pays_codes = faux_pays_df['Country Code'].tolist()
print(f"\nNombre de 'faux pays' identifiés : {len(faux_pays_codes)}")
print("\nListe des codes qui seront utilisés pour le filtrage :")
print(faux_pays_codes)

--- Faux pays identifiés (lignes sans information de Région) ---
    Country Code                                      Short Name Income Group
5            ARB                                      Arab World          NaN
57           EAP           East Asia & Pacific (developing only)          NaN
58           EAS         East Asia & Pacific (all income levels)          NaN
59           ECA         Europe & Central Asia (developing only)          NaN
60           ECS       Europe & Central Asia (all income levels)          NaN
63           EMU                                       Euro area          NaN
68           EUU                                  European Union          NaN
78           GIB                                       Gibraltar          NaN
89           HIC                                     High income          NaN
92           HPC          Heavily indebted poor countries (HIPC)          NaN
116          LAC     Latin America & Caribbean (developing only)          NaN
122          LCN   Latin America & Caribbean (all income levels)          NaN
123          LDC    Least developed countries: UN classification          NaN
124          LIC                                      Low income          NaN
127          LMC                             Lower middle income          NaN
128          LMY                             Low & middle income          NaN
140          MEA  Middle East & North Africa (all income levels)          NaN
143          MIC                                   Middle income          NaN
148          MNA    Middle East & North Africa (developing only)          NaN
157          NAC                                   North America          NaN
166          NRU                                           Nauru          NaN
168          OED                                    OECD members          NaN
187          SAS                                      South Asia          NaN
198          SSA            Sub-Saharan Africa (developing only)          NaN
200          SSF          Sub-Saharan Africa (all income levels)          NaN
225          UMC                             Upper middle income          NaN
234          WLD                                           World          NaN

Nombre de 'faux pays' identifiés : 27

Liste des codes qui seront utilisés pour le filtrage :
['ARB', 'EAP', 'EAS', 'ECA', 'ECS', 'EMU', 'EUU', 'GIB', 'HIC', 'HPC', 'LAC', 'LCN', 'LDC', 'LIC', 'LMC', 'LMY', 'MEA', 'MIC', 'MNA', 'NAC', 'NRU', 'OED', 'SAS', 'SSA', 'SSF', 'UMC', 'WLD']

In [21]:
# --- On commence par nettoyer le dataframe principal des pays ---
print("--- Nettoyage de la table Country ---")
print(f"Dimensions avant nettoyage : {df_country.shape}")
df_country_propre = df_country[~df_country['Country Code'].isin(faux_pays_codes)]
print(f"Dimensions après nettoyage : {df_country_propre.shape}")

# --- Ensuite, on nettoie les autres fichiers de la même manière ---
# NOTE : Vous devrez charger les autres fichiers (Data, FootNote, etc.) au préalable
df_data = pd.read_csv('EdStatsData.csv')
df_footnote = pd.read_csv('EdStatsFootNote.csv')
df_country_series = pd.read_csv('EdStatsCountry-Series.csv')

print("\n--- Nettoyage de la table Data ---")
print(f"Dimensions avant nettoyage : {df_data.shape}")
df_data_propre = df_data[~df_data['Country Code'].isin(faux_pays_codes)]
print(f"Dimensions après nettoyage : {df_data_propre.shape}")

print("\n--- Nettoyage de la table FootNote ---")
print(f"Dimensions avant nettoyage : {df_footnote.shape}")
# Attention, le nom de la colonne est 'CountryCode' (sans espace) dans ce fichier
df_footnote_propre = df_footnote[~df_footnote['CountryCode'].isin(faux_pays_codes)]
print(f"Dimensions après nettoyage : {df_footnote_propre.shape}")

print("\n--- Nettoyage de la table Country-Series ---")
print(f"Dimensions avant nettoyage : {df_country_series.shape}")
# Ici aussi, le nom de la colonne est 'CountryCode'
df_country_series_propre = df_country_series[~df_country_series['CountryCode'].isin(faux_pays_codes)]
print(f"Dimensions après nettoyage : {df_country_series_propre.shape}")

--- Nettoyage de la table Country ---
Dimensions avant nettoyage : (241, 32)
Dimensions après nettoyage : (214, 32)

--- Nettoyage de la table Data ---
Dimensions avant nettoyage : (886930, 70)
Dimensions après nettoyage : (787975, 70)

--- Nettoyage de la table FootNote ---
Dimensions avant nettoyage : (643638, 5)
Dimensions après nettoyage : (516743, 5)

--- Nettoyage de la table Country-Series ---
Dimensions avant nettoyage : (613, 4)
Dimensions après nettoyage : (611, 4)

In [22]:
# La table df_country_propre est déjà notre référence des "vrais pays"
print("--- Utilisation de la table de pays propre comme référence ---")
print(f"Notre table de référence contient {df_country_propre.shape[0]} pays.")

# On ne garde que la colonne qui nous sert de clé de jointure
table_de_reference = df_country_propre[['Country Code']]

# --- Jointure avec la table Data ---
print("\n--- Nettoyage de la table Data par jointure ---")
print(f"Dimensions avant jointure : {df_data.shape}")
df_data_jointure = pd.merge(df_data, table_de_reference, on='Country Code', how='inner')
print(f"Dimensions après jointure : {df_data_jointure.shape}")

# --- Jointure avec la table FootNote ---
print("\n--- Nettoyage de la table FootNote par jointure ---")
print(f"Dimensions avant jointure : {df_footnote.shape}")
# On doit spécifier les noms de colonnes car ils sont différents
df_footnote_jointure = pd.merge(df_footnote, table_de_reference, left_on='CountryCode', right_on='Country Code', how='inner')
print(f"Dimensions après jointure : {df_footnote_jointure.shape}")

# Vous remarquerez que la jointure ajoute une colonne 'Country Code' en double.
# Vous pouvez la supprimer si nécessaire, mais pour le filtrage, ce n'est pas un problème.

--- Utilisation de la table de pays propre comme référence ---
Notre table de référence contient 214 pays.

--- Nettoyage de la table Data par jointure ---
Dimensions avant jointure : (886930, 70)
Dimensions après jointure : (784310, 70)

--- Nettoyage de la table FootNote par jointure ---
Dimensions avant jointure : (643638, 5)
Dimensions après jointure : (515752, 6)